Create core templates
davangcas/blaster_impresiones pull request #27
Opened 2023-07-26 16:50 UTC by lourain124

Create core templates

## Resolves: #7

## Comments
     Se generaron los archivos base necesarios para el proyecto.
     - Se crearon los templates:
        - header.html
        - navbar.html
        - body.html
        - footer.html
        - scripts.js
     - Incluso se identificó cada bloque:
        - Block body
        - Block head
        - block content
        - Block javascript

## Testing

2023-07-26 18:13 UTC, davangcas requested changes

2023-07-26 18:13 UTC, davangcas commented on core/templates/core/body.html
> +<!DOCTYPE html>
De 10!! Esta re bien, pero lo cambiaria de esta forma:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        {% include 'core/styles.html' %}

        {% block styles %}
        {% endblock %}
    </head>
    <body class="hold-transition sidebar-mini layout-fixed">
        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
            {% include 'core/navbar.html' %}
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
            {% include 'core/aside.html' %}
        <!-- /.Main Sidebar Container -->

        <div class="content-wrapper">
            <div class="content-header">
                {% block content_header %}
                {% endblock %}
            </div>
        </div>

        <section class="content">
            {% block content %}
            {% endblock %}
        </section>

        <!-- Footer -->
        {% include 'core/footer.html' %}
        {% include 'core/scripts.html' %}

        {% block scripts %}
        {% endblock %}

    </body>
</html>
```
Para que despues sea un poco mas facil la implementacion de cada seccion
Por ejemplo con el aside, hacerlo en otro archivo
los scripts que van dentro del body
y los bloques serian para poder despues personalizar esas secciones

2023-07-26 19:13 UTC, lourain124 commented on core/templates/core/body.html
> +<!DOCTYPE html>
Dale!! yo no lo amplié más porque no estaba muy especificado, por eso solo realicé lo que decía el issue, ahí lo modifico así quede mejor

2023-07-26 19:58 UTC, davangcas commented on core/templates/core/body.html
> +    {% block content %}
Holaa!! Todo bien? <3, Aqui no es necesario el block content de la linea 34, porque esta dentro el bloque, va a dar error esto, con dejar el que esta dentro de diez

2023-07-26 19:59 UTC, davangcas commented on core/templates/core/header.html
> +<!-- Head -->
Este archivo creo que ya no es necesario

2023-07-26 19:59 UTC, davangcas commented on core/templates/core/header.html
> +<!-- Head -->
No hay problema que el contenido de momento este vacio, es como dejar la estructura total, despues lo vamos a ir modificando

2023-07-26 20:00 UTC, davangcas commented on core/templates/core/navbar.html
> +  <!-- Left navbar links -->
Aqui podemos quizas dejar un solo ejemplo como para despues copiarlo y asi quede como base nomas

2023-07-26 20:01 UTC, davangcas commented on core/templates/core/styles.html
> +{% block styles %}
Aqui no es necesario poner el block styles, lo vamos a usar dentro de otros templates en caso de que tengamos que agregar mas estilos

2023-07-28 17:27 UTC, davangcas commented
Hola @lourain124 ! Como estas? Aqui hago los cambios asi avancemos con los otros issues

2023-07-28 17:27 UTC, merged